const Map<String, String> ar = {
  'Home': 'الرئيسية',
  'My Orders': 'طلباتي',
  'More': 'المزيد',
  'search': 'ابحث عن مكان',
  'View': 'عرض الكل',
  'View All': 'عرض الكل',
  'Skip': 'تخطي',
  'Register': 'انشاء حساب',
  'Don’t have an account? ': 'ليس لديك حساب؟ ',
  'LOGIN': 'دخول',
  'Password required': 'كلمة المرور مطلوبة',
  'Password': 'كلمة المرور',
  'Phone': 'رقم الهاتف',
  'Phone required': 'رقم الهاتف مطلوب',
  'Login': 'تسجيل الدخول',
  'Phone number is wrong': 'رقم الهاتف خاطئ',
  'Password should have atleast 8 characters':'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
  'Enter a stronger password': 'أدخل كلمة مرور أقوى',
  'Your Name': 'الإسم بالكامل',
  'Your Name required': 'الإسم بالكامل مطلوب',
  'required': 'مطلوب *',
  'Sign Up': 'تسجيل',
  'By registering you agree to our': 'بالتسجيل فإنك توافق على',
  'Terms of Service': 'شروط الخدمة',
  ' Privacy Policy': ' سياسة الخصوصية ',
  'Re Password': 'كلمة المرور مرة أخري',
  'Email': 'البريد الألكتروني',
  'Email is wrong': 'البريد الألكتروني خاطئ',
  'Passwords do not match': 'كلمتا المرور غير متطابقتان',
  'Lang': 'اللغة',
  'En': 'الإنجليزية',
  'Ar': 'العربية',
  'Edit Profile': 'تعديل الملف الشخصي',
  'number of Orders': 'عدد الطلبات',
  'Address': 'العناوين',
  'Notices': 'الإشعارات',
  'Settings': 'الإعدادات',
  'Logout': 'تسجيل الخروج',
  'Outher': 'أخري',
  'logout?': ' هل تريد تسجيل الخروج ؟ ',
  'cancel': 'إلغاء',
  'exit': 'خروج',
  'all': 'الكل',
  'filter': 'تصنيف',
  'Quantity': 'الكمية',
  'ok': 'نعم',
  'next': 'التالي',
  'start': 'ابدء الان',
  'welcome': 'مرحبا بك',
  'login_desc': 'هذا النص مثال يمكن ان يستبدل بنص اخر',
  'phone_enter': 'من فضلك أدخل رقم الجوال',
  'send_code': 'إرسال الكود',
  'or': 'أو',
  'is_phone': 'لقد قمت بكتابة رقم',
  'confirm_phone': 'هل أنت متأكد من صحة الرقم ؟',
  'check_acc': 'التحقق من الحساب',
  'code_enter': 'الرجاء إدخال الكود المرسل على رقم الهاتف الخاص بك',
  'code_not_send': 'لم تستلم الكود بعد ؟',
  'code_send_agien': 'أعد إرسال الكود',
  'Done': 'تأكيد',
  'code error': 'الكود الذي أدخلتة خاطئ',
  'explore': 'إستكشف',
  'Arithmetic': 'حسابي',
  'duration': 'المدة : ',
  'hour': ' ساعة ',
  'About as': 'نبذه ',
  'company choose': 'إختيار الشركة',
  'Select the date': 'حدد التاريخ',
  'The number of people': 'عدد الأشخاص',
  'Payment method': 'طريقة الدفع',
  'credit card': 'بطاقة إئتمانية',
  'Credit card payment': 'الدفع بالبطاقة الأئتمانية',
  'cash payment': 'الدفع كاش',
  'Payment by cash': 'الدفع عن طريق الكاش',
  'choose trip date': 'حدد التاريخ',
  'choose paymentType': 'إختر طريقة الدفع',
  'companies': 'الشركات',
  'Complete the order': 'إتمام الطلب',
  'total + tax': 'الإجمالى + الضريبة',
  'Company Profile': 'نبذة عن الشركة',
  'Order details': 'تفاصيل الطلب',
  'the number': 'العدد',
  'the cost': 'التكلفة',
  'Add-ons': 'الأضافات',
  'add promocode': 'إضافة بروموكود',
  'Please enter the code': 'الرجاء أدخال البرموكود',
  'reservation confirmation': 'تأكيد الحجز',
  'Data completion': 'إستكمال البيانات',
  'Account holder information': 'بيانات صاحب الحساب',
  'Please enter the name': 'الرجاء أدخال الأسم',
  'Please enter the site': 'الرجاء أدخال الموقع',
  'detect location': 'تحديد الموقع',
  'Location confirmation': 'تأكيد الموقع',
  'null': 'حدث خطأ ما حاول مجددا',
  'payment': 'الدفع',
  'Your request has been sent successfully': 'تم إرسال طلبك بنجاح',
  'Back to main': 'الرجوع للرئيسية',
  'cash': 'كاش',
  'visa': 'فيزا',
  'Total': 'المجموع',
  'show more': 'إظهار المزيد',
  'location': 'الموقع',
  'Order Summary': 'ملخص الطلب',
  'Value Added': 'القيمة المضافة',
  'change photo': 'تغيير الصورة',
  'The name': 'الإسم',
  'Notice': 'تنوية : ',
  'Notice_desc':'في حالة تعديل الرقم سيتم تسجيل الخروج وإرسال كود التفعيل للرقم الجديد',
  'camera': 'الكاميرا',
  'gallary': 'معرض الصور',
  'Favorite': 'المفضلة',
  'Portfolio': 'المحفظة',
  'Your current balance': 'رصيدك الحالي',
  'Wallet Charging': 'شحن المحفظة',
  'charging_value': 'أدخل القيمة',
  'The Value': 'القيمة',
  'Please enter The Value': 'الرجاء إدخال قيمة الشحن',
  'Connect with us': 'تواصل معنا',
  'whats up': 'الواتساب',
  'Sending a Message': 'إرسال رسالة',
  'send': 'إرسال',
  'the message': 'الرسالة',
  'Please write your message': 'الرجاء كتابة رسالتك',
  'who are we': 'من نحن',
  'About us': 'نبذه عنا',
  'Terms and Conditions': 'الشروط والأحكام',
  'Application language': 'لغة التطبيق',
  'app_lang_desc': 'هذا النص هو مثال يمكن ان يستبدل باي نص',
  'Currency used Desc': 'هذا النص هو مثال يمكن ان يستبدل باي نص',
  'No notifications yet': 'لا توجد إشعارات حتي الأن',
  'No notifications yet Desc':'هذا النص مثال يمكن ان يستبدل باي نص أخر هذا النص مثال يمكن ان يستبدل باي نص أخر',
  'the site done': 'تم تحديد الموقع',
  'sale': 'خصم',
  'day:': 'اليوم : ',
  'Flight time': 'حدد الوقت',
  'Select the time': 'إختر الوقت',
  'from': 'من ',
  'to': ' إلي ',
  'Top Rated': 'الأعلى تقييما',
  'Lowest Rated': 'الأقل تقييما',
  'Highest Price': 'الأعلى سعرا',
  'lowest price': 'الأقل سعرا',
  'name': 'الأسم',
  'promo is active': 'حصلت على خصم : ',
  'Your payment has been sent successfully': 'تم الدفع بنجاح',
  'Your no payment': 'لم يتم الدفع بنجاح',
  'error sent payment': 'حاول مره اخري',
  'Payment by wallet': 'يمكنك الدفع عن طريق المحفظة الأن',
  'choose': 'إختر',
  'Price varies from': 'إختلف السعر إلي',
  'wallet': 'المحفظة',
  'fish code': 'إنتهت صلاحية الرمز',
  'canceled': 'ملغي',
  'no reservations now': 'لا يوجد حجوزات الأن',
  'will be deducted': 'سيتم خصم',
  'Are you sure to cancel': 'هل أنت متأكد من الألغاء؟',
  'comment': 'تعليق',
  'send rating': 'إرسال التقييم',
  'choose persons': 'أختر عدد الأشخاص',
  'Pay again': 'ادفع مرة أخرى',
  'Connect with Google': 'تسجيل الدخول عبر جوجل',
  'Connect with Face': 'تسجيل الدخول باستخدام الفيسبوك',
  'Basic Add-ons no required': 'الإضافات المتاحة',
  'less text': 'أقراء أقل',
  'more text': 'أقراء المزيد',
  'please select a country': 'أختر الدولة',
  'your country': 'دولتك',
  'error_api': 'حدث خطأ ما .. حاول لاحقا',
  'no image selected': 'لم تقم بإختيار اي صورة',
  'Ask for notification status': 'تفعيل الأشعارات',
  'tax': 'الضريبة',
  'total': 'الإجمالي',
  'pat_data': 'بيانات الدفع',
  'error': 'خطأ',
  'error desc': 'حدث خطأ ما نعمل على إصلاحة ..',
  'login with': 'تسجيل الخول بـ',
  'active_phone': 'تفعيل رقم الهاتف',
  'activation': 'تفعيل',
  'Enabled': 'مفعل',
  'choose Basic Add-ons' : 'اختر واحد عالاقل من الاضافات الاساسيه',
  'delete acc' : 'حـذف الحساب',
  'delete acc?' : 'هل تريد حذف الحساب؟',
  'not connected' : 'غير متصل بالشبكة',
  //
  'Time' : 'الوقت',
  // shlat
  'user' : 'مستخدم',
  'provider' : 'بــائــع',
  'Didn’t recieve code?' : 'لم تتلق الرمز؟',
  'Request'  :'. إعادة إرسال',
  'verification code' : 'رمز التحقق',
  'We have sent you the 6-digit code to' : 'لقد أرسلنا لك الرمز المكون من 6 أرقام إلى ',
  'Enter the code below to verify the phone number': 'أدخل الرمز أدناه للتحقق من رقم الهاتف',
  'Im from validator' : 'كود التحقق خاطئ',
  'Please choose the service you provide' : 'من فضلك اختر الخدمة التى تقدمها',
  'Choose the service' :'اختر الخدمه',
  'continuation':'استمرار',
  'Choose on map' : 'اختر على الخريطة',
  'Close' : 'اغلاق',
  'Enter' : 'ادخال',
  'the address' : 'العنوان',
  'Opening date' : 'موعد الافتتاح',
  'Closing time':'موعد الاغلاق',
  'Number of people' : 'عدد الافراد',
  'price' : 'السعر',
  'Booking times in the morning' : 'مواعيد الحجز صباحا',
  'Booking times are in the evening':'مواعيد الحجز مساء',
  'save' : 'حفظ',
  'name one' : 'اسم',
  'al' : 'ال',
  'add' : 'اضافة',
  'Other' : 'اخرى',
  'category name': 'اسم الفئة',
  'Enter category name':'ادخال اسم الفئة',
  'price one' : 'سعر',
  'details' : 'تفاصيل',
  'upload' : 'رفع',
  'image'  :'صوره',
  'delivery price' : 'سعر التوصيل',
  'images' : 'الصور',
  'products' : 'المنتجات',
  'add product' : 'اضافة منتج',
  'edit' : 'تعديل',
  'product name' : 'اسم المنتج',
  'product price' : 'سعر المنتج',
  'product note' : 'نبذة عن المنتج',
  'size price' : 'الحجم و السعر',
  'size' : 'الحجم',
  'addtions price' : 'الاضافات و السعر',
  'addtion' : 'اضافة',
  'product' : 'المنتج',
  'agien' : 'حاول مجددا',
  'edit product' : 'تعديل منتج',
  'place' : 'مكان',
  'Inside the salon':'داخل الصالون',
  'Outside the salon':'خارج الصالون',
  'Personal account' : 'الحساب الشخصى',
  'Your requests' : 'طلباتك',
  'Language and theme settings' : 'اعدادات اللغة و السمة',
  'About the app' :'حول التطبيق',
  'search one' : 'بحث',
  'Other sections': 'اقسام اخرى',
  'price in' : 'السعر يبدء من',
  'SAR' : 'ريال',
  'details in' : 'تفاصيل عن' ,
  'date and time' : 'التاريخ و الوقت',
  'add basket' :'اضافة الى السلة',
  'outher providers' :'ذات صلة',
  'am' : 'صبــاحــاً',
  'pm' : 'مـســاءً',
  'Please log in first' : 'يرجي تسجيل الدخول اولا',
  'Choose morning or evening' : 'اختر صباحا ام مساء',
  'clock' : 'الساعه',
  'Choose size' : ' اختيار الحجم',
  'addtions' :'الاضافات',
  'Choose package' : 'اختر الباقه',
  'Categories' : 'الفئات',
  'Add note' : 'اضافة ملحوظة',
  'You can add your notes here' : 'يمكنك اضافة ملحوظاتك هنا',
  'Services' : 'الخدمات',
  'basket' : 'السلة',
  'Learn and manage your chosen services and products' : 'استعرف وأدير الخدمات والمنتجات التي اخترتها',
  'Delete cart' : 'حذف السلة',
  'Are you sure you want to delete all basket items?' : 'هل انت متأكد انك تريد حذف جميع عناصر السلة ؟',
  'delete' : 'حذف',
  'Your basket is empty' : 'سلتك فارغة',
  'Explore services and products to add items':' استكشف الخدمات والمنتجات لإضافة العناصر',
  'Subtotal':'الإجمالى الفرعي',
  'shipping fees' : 'رسوم الشحن',
  'application' : 'تطبيق',
  'Enter promo code' : 'ادخل الرمز الترويجي',
  'after discount' : 'بعد الخصم',
  'You saved' : 'لقد وفرت',
  'payment methods' : 'طرق الدفع',
  'An individual' : 'فرد',
  'for every' : 'لكل',
  'Applied' : 'مُطبَّق',
  'Login page desc' : 'ادخل رقم الهاتف',
  'You can join us as a service provider' : 'يمكنك الانضمام لنا كمقدم خدمه ',
  'from here' : 'من هنا',
  'do you have an account ?' : 'هل لديك حساب ؟',
  'add data' : 'اضف بياناتك',
  'You can skip' : 'يمكنك التخطي ',
  'You are not logged in' : 'لم تسجل دخول',
  'Your favorites will be added after logging in' : 'سيتم اضافه المفضلين لك بعد تسجيل الدخول',
  'Favorites are empty' : 'المفضله فارغه',
  'Add your favorites and they will appear here' : 'قم باضافه المفضلين لك وسيظهرون هنا',
  'About the Sahalat application' : 'نبذة عن تطبيق جمالك',

 };
