const Map<String, String> en = {
  'Home': 'Home',
  'My Orders': 'My trips',
  'article': 'Article',
  'More': 'More',
  'search': 'Search',
  'View': 'View',
  'View All': 'View All',
  'Skip': 'Skip',
  'Register': 'Register',
  'Don’t have an account? ': 'Don’t have an account? ',
  'LOGIN': 'LOGIN',
  'Password required': 'Password required',
  'Password': 'Password',
  'Phone': 'Phone',
  'Phone required': 'Phone required',
  'Login': 'Login',
  'Phone number is wrong': 'Phone number is wrong',
  'Password should have atleast 8 characters':'Password should have atleast 8 characters',
  'Enter a stronger password': 'Enter a stronger password',
  'Your Name': 'Your Name',
  'Your Name required': 'Your Name required',
  'required': 'required *',
  'Sign Up': 'Sign Up',
  'By registering you agree to our': 'By registering you agree to our',
  'Terms of Service': 'Terms of Service',
  ' Privacy Policy': ' Privacy Policy ',
  'Re Password': 'Re Password',
  'Email': 'Email',
  'Email is wrong': 'Email is wrong',
  'Date of Birth': 'Date of Birth',
  'Passwords do not match': 'Passwords do not match',
  'Lang': 'Language',
  'En': 'English',
  'Ar': 'Arabic',
  'Edit Profile': 'Edit Profile',
  'Favorite products': 'Favorite products',
  'number of Orders': 'Number of Orders',
  'number of prescriptions': 'Nmber of prescriptions',
  'Address': 'Address',
  'Notices': 'Notices',
  'Settings': 'Settings',
  'Logout': 'Logout',
  'Outher': 'Outher',
  'logout?': ' Do you want to log out? ',
  'cancel': 'Cancel',
  'exit': 'Exit',
  'all': 'ALL',
  'filter': 'filter',
  'Quantity': 'Quantity',
  'ok': 'yes',
  'next': 'next',
  'start': 'Start your experience now',
  'welcome': 'welcome',
  'login_desc': 'This example text can be replaced by another text',
  'phone_enter': 'Please enter your mobile number',
  'send_code': 'send code',
  'or': 'or',
  'is_phone': 'You typed a number',
  'confirm_phone': 'Are you sure the number is correct?',
  'check_acc': 'check account',
  'code_enter': 'Please enter the code sent to your phone number',
  'code_not_send': 'You havent received the code yet?',
  'code_send_agien': 'resend code',
  'Done': 'confirm',
  'code error': 'The code you entered is wrong',
  'explore': 'Explore',
  'my reservations': 'Reservations',
  'Arithmetic': 'My account',
  'duration': 'duration :',
  'hour': 'hour',
  'new articals': 'latest articles',
  'trips_new': 'recent trips',
  'About as': 'About ',
  'company choose': 'company choose',
  'trip_desc': 'trip details',
  'Program description': 'Program description',
  'Program Rules': 'Program Rules',
  'Program Prohibitions': 'Prohibitions',
  'Flight date': 'Trip date',
  'Select the date': 'Select the date',
  'The number of people': 'number of people',
  'adults': 'adults',
  'adults_age': '(age 10-90 )',
  'kids': 'kids',
  'kids_age': '(age less than 10 )',
  'Basic Add-ons': 'Basic Add-ons',
  'Payment method': 'Payment method',
  'credit card': 'credit card',
  'Credit card payment': 'Credit card payment',
  'cash payment': 'cash payment',
  'Payment by cash': 'Payment by cash',
  'choose trip date': 'select the date',
  'choose paymentType': 'choose payment method',
  'companies': 'companies',
  'Completed booking': 'Completed booking',
  'Complete the order': 'Complete the order',
  'total + tax': 'total + tax',
  'Company Profile': 'Company Profile',
  'Order details': 'Order details',
  'the number': 'the number',
  'the cost': 'the cost',
  'number of children': 'number of children',
  'Adult': 'adult',
  'Child': 'child',
  'Add-ons': 'Add-ons',
  'add promocode': 'add promocode',
  'Please enter the code': 'Please enter the code',
  'reservation confirmation': 'reservation confirmation',
  'Data completion': 'Data completion',
  'Account holder information': 'Account holder information',
  'Please enter the name': 'Please enter the name',
  'Please enter age': 'Please enter age',
  'age': 'age',
  'Please enter the ID number': 'Please enter the ID number',
  'ID number': 'ID number',
  'Please enter the site': 'Please enter the site',
  'detect location': 'detect location',
  'Location confirmation': 'Location confirmation',
  'Adult facilities data': 'Adult facilities data',
  'Childrens data': 'Childrens data',
  'Please select a nationality': 'Please select a nationality',
  'Please enter the room number': 'Please enter the room number',
  'room number': 'room number',
  'Data of adult escorts is required': 'Data of adult escorts is required',
  'Information of accompanying children is required':'Child escort data is required',
  'null': 'Something went wrong, try again',
  'payment': 'payment',
  'Your request has been sent successfully':'Your request has been sent successfully',
  'successfully sent':'Congratulations, your request has been successfully sent, you can follow up on your booking through the My Bookings field',
  'Back to main': 'Back to main',
  'My existing reservations': 'Existing',
  'My new bookings': 'New Bookings',
  'My completed reservations': 'Completed',
  'Flight Number': 'Trip number',
  'cash': 'cash',
  'visa': 'visa',
  'Booking details': 'Booking details',
  'Total': 'total',
  'show more': 'show more',
  'flight rescheduled': 'trip rescheduled',
  'people details': 'people details',
  'Nationality': 'Nationality',
  'location': 'location',
  'Order Summary': 'Order Summary',
  'Value Added': 'Value Added',
  'change photo': 'change photo',
  'The name': 'The name',
  'Notice': 'Notice :',
  'Notice_desc':'In case the number is modified, the checkout will be logged and the activation code will be sent to the new number.',
  'camera': 'camera',
  'gallary': 'gallery',
  'Favorite': 'Favorite',
  'Portfolio': 'Portfolio',
  'Your current balance': 'Your current balance',
  'Wallet Charging': 'Wallet Charging',
  'charging_value': 'Enter the value',
  'The Value': 'The Value',
  'Please enter The Value': 'Please enter the shipping value',
  'Connect with us': 'Connect with us',
  'whats up': 'whats up',
  'Sending a Message': 'Sending a Message',
  'send': 'send',
  'the message': 'the message',
  'Please write your message': 'Please write your message',
  'who are we': 'who are we',
  'About us': 'About us',
  'Terms and Conditions': 'Terms and Conditions',
  'Application language': 'Application language',
  'app_lang_desc': 'This text is an example that can be replaced with any text',
  'the currency': 'the currency',
  'Currency used': 'Currency used',
  'Currency used Desc':'This text is an example that can be replaced with any text',
  'No notifications yet': 'No notifications',
  'No notifications yet Desc':'This example text can be replaced by any other text This example text can be replaced by any other text',
  'the site done': 'Location selected',
  'sale': 'sale',
  'day:': 'Today : ',
  'Flight time': 'set time',
  'Select the time': 'Choose the time',
  'from': 'from ',
  'to': ' to ',
  'Top Rated': 'Top Rated',
  'Lowest Rated': 'Lowest Rated',
  'Highest Price': 'Most price',
  'lowest price': 'lowest price',
  'choose additions': 'Choose add-ons',
  'name': 'The name',
  'promo is active': 'I got a discount: ',
  'Your payment has been sent successfully': 'Payment completed successfully',
  'Your no payment': 'Payment not completed successfully',
  'error sent payment':'Try again',
  'Payment by wallet': 'You can pay by wallet now',
  'no wallet price':'Payment has been transferred to cash due to insufficient balance',
  'babys': 'infants',
  'babys_age': '(age is less than 2 years)',
  'Baby': 'infant',
  'choose': 'Choose',
  'change price for nationality':'The price will vary according to nationality',
  'Price varies from': 'The price is different',
  'no articals now': 'There are no articles for now',
  'no trips now': 'There are no trips now',
  'The number of add': 'number of additions',
  'wallet': 'Wallet',
  'fish code': 'Code has expired',
  'canceled': 'canceled',
  'no reservations now': 'No reservations now',
  'will be deducted': 'will be deducted',
  'From the value of the reservation': 'From the value of the reservation',
  'Are you sure to cancel': 'Are you sure to cancel?',
  'comment': 'Comment',
  'Write a comment for the company': 'Write a comment for the company',
  'Please rate the company': 'Please rate the company',
  'Please rate the trip': 'Please rate the trip',
  'send rating': 'Submit rating',
  'chosse rate': 'Choose the appropriate rating',
  'choose persons': 'Choose the number of people',
  'Pay again': 'Pay again',
  'Connect with Google': 'Login with Google',
  'Connect with Face': 'Login with Facebook',
  'Basic Add-ons no required': 'Available add-ons',
  'less text': 'read less',
  'more text': 'read more',
  'please select a country': 'Select the country',
  'your country': 'your country',
  'error_api': 'Something went wrong..try later',
  'no image selected': 'no image selected',
  'Ask for notification status': 'Activate notifications',
  'tax': 'tax',
  'total': 'total',
  'no companies now': 'no companies now',
  'pat_data': 'Payment data',
  'error': 'error',
  'error desc': 'Something went wrong we are working on..',
  'login with': 'Sign in with',
  'active_phone': 'Activate the phone number',
  'activation': 'Activation',
  'Enabled': 'Enabled',
  'vodafone': 'vodafone cash',
  'vodafone cash payment': 'Pay with vodafone Cash',
  'no company now': 'There are no offers now',
  'choose Basic Add-ons' : 'Choose at least one of the basic add-ons',
  'no wallet this phone' : 'You do not have a wallet for this number',
  'delete acc' : 'delete account',
  'delete acc?' : 'Do you want to delete the account?',
  'not connected' : 'not connected',
  'Time' : 'Time',
  // shlat
  'user' : 'user',
  'provider' : 'provider',
  'Didn’t recieve code?' : 'Didn’t recieve code?',
  'Request'  :'. Resend',
  'verification code' : 'verification code',
  'We have sent you the 6-digit code to' : 'We have sent you the 6-digit code to',
  'Enter the code below to verify the phone number': 'Enter the code below to verify the phone number',
  'Im from validator' : 'Invalid verification code',
  'Please choose the service you provide' : 'Please choose the service you provide',
  //
  'Choose the service': 'Choose the service',
   'continuation':'continuation',
   'Choose on map': 'Choose on map',
   'Close' : 'Close',
   'Enter': 'Enter',
   'the address' : 'address',
   'Opening date': 'Opening date',
   'Closing time':'Closing time',
   'Number of people' : 'Number of people',
   'price' : 'price',
   'Booking times in the morning': 'Booking times in the morning',
   'Booking times are in the evening':'Booking times are in the evening',
   'save' : 'save',
   'name one' : 'name',
   'al' : 'the',
   'add' : 'add',
   'Other' : 'other',
   'category name': 'category name',
   'Enter category name':'Enter category name',
   'price one' : 'price',
   'details' : 'details',
   'upload' : 'upload',
   'image' :'image',
   'delivery price' : 'delivery price',
   'images' : 'images',
   'products' : 'products',
   'add product' : 'Add product',
   'edit' : 'edit',
   'product name' : 'product name',
   'product price' : 'product price',
   'product note' : 'About the product',
   'size price' : 'size and price',
   'size' : 'size',
   'addtions price': 'addtions and price',
   'addtion' : 'add',
   'product' : 'product',
   'agien': 'try again',
   'edit product' : 'edit product',
   'place' : 'place',
   'Inside the salon':'Inside the salon',
   'Outside the salon':'Outside the salon',
   'Personal account': 'Personal account',
   'Your requests' : 'Your requests',
   'Language and theme settings': 'Language and theme settings',
   'About the app': 'About the app',
   'search one' : 'search',
   'Other sections': 'Other sections',
   'price in' : 'price starts from',
   'SAR' : 'SAR',
   'details in' : 'details about',
   'date and time' : 'date and time',
   'add basket': 'Add to basket',
   'outher providers' :'related',
   'am': 'morning',
   'pm' : 'evening',
   'Please log in first': 'Please log in first',
   'Choose morning or evening': 'Choose morning or evening',
   'clock' : 'clock',
   'Choose size': 'Choose size',
   'addtions' :'additions',
   'Choose package': 'Choose package',
   'Categories': 'Categories',
   'Add note': 'Add a note',
   'You can add your notes here': 'You can add your notes here',
   'Services' : 'Services',
   'basket' : 'basket',
   'Learn and manage your chosen services and products': 'Learn and manage your chosen services and products',
   'Delete cart': 'Delete cart',
   'Are you sure you want to delete all basket items?' : 'Are you sure you want to delete all basket items?',
   'delete' : 'delete',
   'Your basket is empty' : 'Your basket is empty',
   'Explore services and products to add items':'Explore services and products to add items',
   'Subtotal':'Subtotal',
   'shipping fees' : 'shipping fees',
   'application' : 'Enter',
   'Enter promo code': 'Enter promo code',
   'after discount' : 'after discount',
   'You saved': 'You saved',
   'payment methods' : 'payment methods',
   'An individual': 'an individual',
   'for every' : 'for every',
   'Applied': 'Applied',
   'Login page desc': 'Enter phone number',
   'You can join us as a service provider': 'You can join us as a service provider ',
   'from here' : 'from here',
   'do you have an account ?' : 'do you have an account ? ',
   'add data': 'Add your data',
   'You can skip': 'You can skip',
   'You are not logged in' : 'You are not logged in',
   'Your favorites will be added after logging in': 'Your favorites will be added after logging in',
   'Favorites are empty' : 'Favorites are empty',
   'Add your favorites and they will appear here': 'Add your favorites and they will appear here',
   'About the Sahalat application': 'About the Sahalat application'
};
